name: CI

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_EC2_METADATA_DISABLED: true

jobs:
 deploy-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: install terraform 
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      #     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      #     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      #     sudo apt-get update && sudo apt-get install terraform
      #     terraform --version

      - name: aws workflow
        run: |
          pwd
          cd frontEndJS
          pwd
          aws s3 mb s3://caleb-varghese-resume-website-bucket --region us-east-1
          aws s3 website s3://caleb-varghese-resume-website-bucket --index-document index.html --error-document index.html
          cd ../backEnd
          pwd
          aws s3api put-bucket-policy --bucket caleb-varghese-resume-website-bucket --policy file://policy.json

      # - name: terraform workflow
      #   run: |
      #     echo terraform workflow
      #     pwd
      #     cd backEnd/terraform
      #     terraform init
      #     terraform validate
      #     terraform fmt


